xiv-gear-planner/gear-planner

src/scripts/sims/ast_sheet_sim.ts, src/scripts/sims/buffs.ts, src/scripts/sims/components/ability_used_table.ts, src/scripts/sims/sch_sheet_sim.ts, src/scripts/sims/sge_sheet_sim_mk2.ts, src/scripts/sims/sim_processors.ts, src/scripts/sims/sim_types.ts, src/scripts/sims/whm_new_sheet_sim.ts, src/scripts/simulation.ts, src/scripts/xivconstants.ts, src/style.less
Builds off of https://github.com/xiv-gear-planner/gear-planner/pull/13
Mayceia reworked the buff processing so that each buff can have a unique activation time, and you no longer need to call `activateBuffs`. This takes that work and adds more handling for buffs being applied by the class being simmed.
Cycle processor abilities can now indicate that they apply a specific buff. This buff can be a pre-existing raid-buff, or a buff unique to that ability (in which case, it can simply be defined inline a la PoM). If it is a normal raid buff (i.e. shows up in the buff picker UI), then it should be passed into the `manuallyActivatedBuffs` parameter of `CycleProcessor`. This will omit them from the normal buff activation. 
This PR also improves behavior with regards to when buffs are checked. …
=> Buff logic rework

.gitignore, src/scripts/sims/ast_sheet_sim.ts, src/scripts/sims/buffs.ts, src/scripts/sims/rpr_sheet_sim.ts, src/scripts/sims/sch_sheet_sim.ts, src/scripts/sims/sim_processors.ts, src/scripts/sims/sim_types.ts, src/scripts/sims/whm_new_sheet_sim.ts, src/scripts/simulation.ts
Initial support for reaper.
uses the Multicycle class to simulate the rotation
This includes a change to how `CycleProcessor.useGcd` calculates the gcd, because it previously just used `stats.gcdMag`. This required adding `attackType` to `Ability`, in addition to just `DamagingAbility`, because not all gcds are damaging (e.g. Healing spells, Form shift, NIN mudras, Dances). There's probably a much better way to implement it than duplicating the field in `Ability` that i'd be down to implement, i'd just need a bit of guidance on how to do so. I modified the other sim sheets to include the new field.
Death's design was also added as a buff. i gave it a 1min duration for the time being because it shakes out the same and not mattering as long as the rotation is done right. I'm not sure if …
=> Rpr support

src/scripts/datamanager.ts, src/scripts/gear.ts, src/scripts/xivconstants.ts
Expects #46.
Implements the BLU weapon damage modifier as described in ["BLU Mage Damage Formula"](https://docs.google.com/document/d/1-NBJDkyl8h_UXFcOba-CrPPcFXZrDs2QXX53pSS3QJc) and discussions from the Allagan Studies Discord.  Also corrects a bug that was filtering out all BLU weapons from gear selection.
Known general limitations:
- The current Xivgear damage formula implementation uses non-caster order of operations.  This causes small amounts of error for all caster actions (limited testing shows <1% deviation).
- The current Xivgear damage formula implementation does not account for the low potency (<100) modifier.  This causes small amounts of error for all jobs with <100 potency actions (limited testing shows <1% deviation).
=> Implement BLU weapon damage modifier

src/scripts/sims/common/swiftcast.ts, src/scripts/sims/common/utils.ts, src/scripts/sims/sim_processors.ts, src/scripts/sims/sim_types.ts, src/scripts/test/sim_tests.ts
- Adds supports for buffs removing themselves arfter snapshot or damage calc
- Allows buffs to modify final damage
- Adds buffs to filter which abilities they will apply to
- Adds support for buffs forcing a crit or dh
Closes #44
=> More oneshot buff support

src/scripts/test/sim_tests.ts, src/scripts/xivmath.ts
`f(AUTO)` should use the appropriate job modifier for auto attacks.
=> Fix bug in auto-attack damage calculation

src/scripts/sims/rpr_sheet_sim.ts, src/scripts/simulation.ts
- More tsdocs in simulation.ts
- Fixes RprSheetSim's shortName
- make Simulation.shortName readonly
- Fix missing return type on SimSpec.loadSavedSimInstance()
=> Better documentation for sims and some minor fixes

src/scripts/datamanager.ts, src/scripts/geartypes.ts, src/scripts/relicstats/relicstats.ts, src/scripts/xivconstants.ts, src/style.less
Prohibits putting invalid stats (i.e. dhit on tank/healer) on relics. 
Closes #41
=> Further relic stat validation behavior

package.json, src/scripts/sims/sim_processors.ts, src/scripts/test/sims/common_values.ts, src/scripts/test/sims/cooldown_tests.ts, src/scripts/test/sims/cycle_processor_tests.ts, src/scripts/test/sims/sim_test_utils.ts, src/scripts/test/sims/sim_tests.ts
- Adds support for custom subclasses and custom creation of CycleProcessor
- This acts as a convenient place to hold 'rotation state' rather than doing it on the Sim class directly
- Split up sim_tests.ts
=> Custom cycle processor support

src/scripts/sims/ast_sheet_sim.ts, src/scripts/sims/buffs.ts, src/scripts/sims/common/swiftcast.ts, src/scripts/sims/party_comp_settings.ts, src/scripts/sims/sim_processors.ts, src/scripts/sims/sim_types.ts, src/scripts/sims/whm_new_sheet_sim.ts, src/scripts/test/sim_test_utils.ts, src/scripts/test/sim_tests.ts, src/scripts/test/sims/common_values.ts, src/scripts/test/sims/sim_test_utils.ts
Splits Buffs into BaseBuff and PartyBuff so that personal-only buffs do not need to specify useless fields such as job and CD.
Closes #60
=> Split buffs into personal and party types

src/scripts/components.ts, src/scripts/xivconstants.ts
Level 80's default item display settings are tailored for TEA since that's the most common reason you would use a level 80 sync. BLU relevant gear is 520-535.
=> BLU ilvl display fix

src/scripts/sims/sim_processors.ts, src/scripts/sims/sim_types.ts
Unifies useGcd and useOgcd, moves cast-related fields up to BaseAbility.
This allows oGCDs to have a cast time.
Closes #56
=> Add support for casted oGCDs

packages/frontend/src/scripts/sims/sim_processors.ts, packages/frontend/src/scripts/sims/sim_types.ts, packages/frontend/src/scripts/test/sims/ability_helpers.ts, packages/frontend/src/scripts/test/sims/combo_test.ts
This supports defining multiple sets of combos on an ability, for corner cases like Gnashing Fang where you need to have two "combo" states being tracked at the same time, and have fine-grained control over which combos are canceled by what.
=> Combo support

packages/frontend/src/style.less
- Slightly improves modal display
- Fixes #102 by adding a hover color to relic stat inputs
- Restores de-emphasis of "No item" or "No materia" messages under an item table
=> Minor UI improvements

packages/frontend/src/scripts/sims/blu/blu_common.ts, packages/frontend/src/scripts/sims/cycle_settings.ts, packages/frontend/src/scripts/sims/sim_processors.ts
Closes #100 
Override `get useAutosByDefault()` to control behavior.
In a future version, it could automatically disable for all healers and casters.
=> Property to allow autoattacks to be disabled by default in a cycle sim

packages/core/src/sims/common/cooldown_manager.ts, packages/core/src/sims/sim_types.ts, packages/frontend/src/scripts/test/sims/cooldown_tests.ts
Adds `sharesCooldownWith` field to `Cooldown`. If you want A, B, C, and D to have shared cooldowns, then B/C/D should have `sharesCooldownWith: A`.
The source and target cooldowns can have different CDs. If one has a 60s CD, and one has a 120s CD, then the cooldown time will be derived from whichever you actually use. That is, using the first skill would block both skills for 60s, and using the second would block both skills for 120s.
Behavior is undefined for abilities with more than one charge.
=> Shared cooldown support

packages/frontend/src/scripts/test/sims/cycle_processor_tests.ts, packages/math-frontend/src/scripts/mathpage/math_ui.ts, packages/xivmath/src/xivmath.ts, packages/xivmath/src/xivstats.ts
Also updates tests, and implements the 'flp' function that floors to a certain precision. 
e.g. `flp(3, value)` will floor to 3 places, i.e. the equivalent of `fl(value * 1000) / 1000`.
=> Implement caster variant of damage formula

packages/core/src/sims/ability_helpers.ts, packages/core/src/sims/sim_types.ts, packages/frontend/src/scripts/test/sims/combo_test.ts
The former default behavior of GCDs always interrupting combos changes in this PR. GCDs now behave the same as oGCDs, i.e. they will not interact with the combo system by default at all. However, if you specify any combo on a GCD, it will still interrupt *other* combos.
=> More combo documentation and make GCDs not interrupt by default in some circumstances

packages/common-ui/styles/common.less
Will now correctly ellipsis long names:
Will also expand/shrink a bit more with the screen width:
=> Make ability column width smarter

packages/frontend/src/scripts/sims/blu/blu_common.ts, packages/frontend/src/scripts/sims/sim_processors.ts, packages/frontend/src/scripts/test/sims/cycle_processor_tests.ts
Auto-attacks will default to on for melee/range/tank, off for healer/caster.
=> Make auto-attacks default based on role

packages/core/src/sheet.ts, packages/core/src/sims/cycle_sim.ts, packages/core/src/util/array_utils.ts, packages/frontend/src/scripts/base_ui.ts, packages/frontend/src/scripts/sims/healer/sge_sheet_sim_mk2.ts, packages/frontend/src/scripts/sims/processors/count_sim.ts, packages/frontend/src/scripts/sims/sim_processors.ts, packages/frontend/src/scripts/test/sims/sim_test_utils.ts
Now supports naming rotations + displays which rotation was used if a sim has multiple:
Cycle sim results now contain all rotations' individual results for future UI use.
Cleaned up some unnecessary tracing.
Sim execution should also have less of an impact on page load times.
=> Improve multi-rotation support

packages/frontend/src/scripts/sims/default_sims.ts, packages/frontend/src/scripts/sims/tank/pld/pld_actions.ts, packages/frontend/src/scripts/sims/tank/pld/pld_buffs.ts, packages/frontend/src/scripts/sims/tank/pld/pldsks_sim.ts
Hello, I have made a paladin simulator that aims to demonstrate the limited but attainable benefits of skill speed via effectively executing a variety of strategies.
I've marked it as a non default sim for PLD as this a) isn't an infinite dummy model, and b) PLD is going to be a 2.50 GCD job as soon as it can be - as such, Nikroulah's PLD cycle sim is a much better tool to select a BIS gearset. However, it's still quite easy to add this one, if desired, and ensures that people see its copious description. It is intended more of a playground to test the impact of non-optimal behaviors, as well as demonstrate possible approaches to situations outside of the norm - showing the impact of mistakes as much as it aims to show any benefits.
It is not abnormal to find the Skill Speed stat on ones …
=> Paladin Skill Speed Simulator

packages/frontend/src/scripts/sims/ranged/dnc_sim.ts, packages/frontend/src/scripts/sims/tank/pld/pld_usage_sim_no_sks.ts
auto potency based on auto delay is actually baked into the auto dmg calculation, so the number of usages should be based on the actual number of autos rather than the normalized p/3s "usages"
=> Fix DNC auto usages

packages/core/src/sims/ability_helpers.ts, packages/core/src/sims/cycle_sim.ts, packages/frontend/src/scripts/sims/healer/sge_sheet_sim_mk2.ts
Refactors SGE sim to use phlegma and psyche when they are ready. Tries to always weave psyche with phlegma since the larger weave window means less likelihood of drift.
Also adds a new method to CycleProcessor - `canUseCooldowns` which takes a GCD and optionally oGCDs. It will determine if the GCD and all of the oGCDs (in order) can be used without violating cooldowns and without clipping. This considers the possibility of delaying an oGCD until later in the weave window if it would not otherwise be off CD.
=> Have sage sim respect cooldowns/drift

packages/frontend/src/scripts/components/export_controller.ts
Allows you to pop open the export modal by calling `startExport(currentSheet)` (for whole sheet) or `startExport(currentGearSet)` (for the currently-selected set).
=> Allow exporting from console

packages/core/src/sims/common/potion.ts, packages/frontend/src/scripts/sims/melee/nin/nin_lv100_sim.ts, packages/frontend/src/scripts/sims/melee/rpr/rpr_actions.ts, packages/frontend/src/scripts/sims/melee/rpr/rpr_sheet_sim.ts, packages/frontend/src/scripts/sims/melee/sam/rotations/sam_lv100_200.ts, packages/frontend/src/scripts/sims/melee/sam/rotations/sam_lv100_207.ts, packages/frontend/src/scripts/sims/melee/sam/rotations/sam_lv100_214.ts, packages/frontend/src/scripts/sims/melee/vpr/vpr_sheet_sim.ts
This PR Adjusts the potion exports so that there is one generic "max level" potion. This way, sims that only care to use the max grade potion available do not need to be updated every time the game adds a new potion.
I have also exported a few extra variables, so that sims could add settings in the future that would allow users to configure which grade potion they would like to use.
=> Adjust potion exports

packages/core/src/datamanager.ts, packages/core/src/external/xivapi.ts
Title. This is a pretty naive implementation, but should at least _help_ remedy the current hug of death y'all sending to the beta.
Just using the `rows=` query parameter to consolidate the `ItemFood` requests into one batch, rather than a seperate request per item. Each request has a bit of overhead I can't do much to avoid, so this should reduce the load a little.
Linting seems to be complaining about something I don't have the brain space to deal with right now.
=> Consolidate ItemFood requests into single batch

packages/frontend/src/scripts/components/draghelpers.ts
The cursor style applied while dragging was not getting removed causing the grabbing hand to always be applied.
1. Create or use a sheet with more than 2 gearsets
2. Drag one of the sets
3. Ensure the grabbing hand does not remain stuck on after dropping the gearset
=> Fix dragging hand getting stuck on

packages/core/src/datamanager.ts, packages/core/src/gear.ts, packages/core/src/test/general_stats_tests.ts, packages/frontend/src/scripts/components/sheet.ts, packages/frontend/src/scripts/test/sims/common_values.ts, packages/frontend/src/scripts/test/sims/cycle_processor_tests.ts, packages/xivmath/src/xivconstants.ts, packages/xivmath/src/xivstats.ts
Fixes issue with order of operations when computing vit when you have both food and a party bonus.
=> Fix vit order

packages/core/src/customgear/custom_item.ts, packages/core/src/datamanager.ts, packages/core/src/datamanager_new.ts, packages/core/src/datamanager_xivapi.ts, packages/core/src/sheet.ts, packages/core/src/test/custom_items_test.ts, packages/frontend/src/scripts/components/custom_item_manager.ts
The item level box has a "cap" checkbox which will cause it to respect item level caps:
You will get a validation error (which you can ignore - it does not block saving) if there is no known ilvl data for the chosen item level:
Existing custom items will default to ignoring caps, while new ones will default to respecting caps.
Closes #259
=> Add ability to have stat caps on custom items

packages/core/src/sims/cycle_sim.ts, packages/frontend/src/scripts/sims/sim_processors.ts, packages/frontend/src/scripts/test/sims/cycle_processor_tests.ts
Closes #282 
Changes the effective duration to be the smaller of the sim's current time (in case the rotation did not specify any more abilities to use) or the specified time, since it already pro-rates incomplete GCDs.
=> Fix sim end time

packages/frontend/src/scripts/sims/tank/pld/pldsks_sim.ts
If the phase was set to end at a particular point, the sim would nearly infinite loop as it found it could fit an 100k+ GCDs into FOF, which would be far more SKS than anyone could reasonably meld...
Since the GCDs took place after time had ended, the sim still calculated DPS correctly. However, opening the sim's table of events would cause the browser to go OOM as it tried to also render 100k comments.
=> Fix for Pld SKS Sim near Infinite Loop

packages/core/src/datamanager_xivapi.ts, packages/core/src/sheet.ts, packages/core/src/sims/common/potion.ts, packages/core/src/sims/sim_types.ts, packages/core/src/sims/sim_utils.ts, packages/frontend/src/scripts/sims/healer/sge_sheet_sim.ts, packages/frontend/src/scripts/sims/healer/whm_sheet_sim.ts, packages/xivmath/src/geartypes.ts, packages/xivmath/src/xivconstants.ts, packages/xivmath/src/xivstats.ts
Refactors ComputedSetStats to have a new class `ComputedSetStatsImpl` handle most of the logic.
`ComputedSetStats` is now immutable, but has a `withModifications` method that returns a clone with the given modifications. Only "safe" modifications are allowed, but more modification points can be added later. 
This keeps ComputedSetStats objects in a consistent state. Take potions for example. Previously, the potion would apply its buff to the main stat, but then the potion logic had to recompute the main stat multiplier and AA multiplier manually. Now, this should happen automatically.
Closes #132
=> Refactor ComputedSetStats

packages/core/src/datamanager_new.ts, packages/data-api-client/src/dataapi.ts, packages/xivmath/src/geartypes.ts
Depends on https://github.com/xiv-gear-planner/xivgear-data-api/pull/2
Mostly closes #302 - it works for the most common gear sources.
Also adds Criterion as a source.
Can't finish with this because SpecialShop is the worst sheet in the game and there is no performant way to query it.
=> Re-enable gear acqusition source (partial)

packages/common-ui/styles/common.less, packages/core/src/gear.ts, packages/core/src/materia/materia_utils.ts, packages/core/src/sheet.ts, packages/core/src/test/materia_memory_test.ts, packages/frontend/src/scripts/components/items.ts, packages/frontend/src/scripts/components/materia.ts, packages/frontend/src/scripts/components/sheet.ts, packages/xivmath/src/geartypes.ts
Adds new materia fill options (names TBD):
TODO: 
Closes #254
=> Expand materia auto-fill settings

packages/frontend/src/scripts/components/sheet.ts
Causes the green-red gradient to cut off for tiny differences, rather than making one set bright green and one bright red when they have an ignorable difference  between them.
Currently, the threshold for using the full gradient is 0.1%. That is, if the worst set is only 0.07% lower DPS than the best set, then the worst set will only be "70% red" rather than 100% red like it was before. If the difference is greater than 0.1%, then the behavior should be the same as before.
Closes #315
=> Reducegradient for miniscule differences in DPS

packages/core/src/customgear/custom_item.ts, packages/core/src/datamanager_new.ts, packages/core/src/datamanager_xivapi.ts, packages/core/src/materia/materia_utils.ts, packages/core/src/sheet.ts, packages/core/src/test/materia_memory_test.ts, packages/data-api-client/src/dataapi.ts, packages/frontend/src/scripts/components/materia.ts, packages/xivmath/src/geartypes.ts
Currently, maximum materia level is only determined by sheet level. Instead, it should be determined by the ilvl of the item it is being equipped into. This affects both manual picking and auto-fill.
=> Make materia selection respect ilvl

eslint.config.js
Per [https://typescript-eslint.io/packages/parser/#project](https://typescript-eslint.io/packages/parser/#project), 
> If you use project references, TypeScript will not automatically use project references to resolve files. This means that you will have to add each referenced tsconfig to the project field either separately, or via a glob.
Furthermore, per typescript-eslint documentation, 
> [parserOptions.projectService](https://typescript-eslint.io/packages/parser#projectservice) is the recommended parser option to enable typed linting as of typescript-eslint v8. It enforces projects generate type information for typed linting from the same tsconfig.json files used by editors such as VS Code.
This PR enables `parserOptions.projectService`.  Per the typescript-eslint documentation, …
=> Resolve ESLint errors

packages/xivmath/src/xivconstants.ts
#328 
UWU/UCOB gearset calculations are inaccurate, giving a 2.00 base GCD that should be higher / slower.
=> Add monk haste for all levels of Greased Lightning

packages/core/src/sheet.ts
Fixes #326 
Now, the logic should be the same for all items - it will show the maximum tier of materia available on that item, and the three tiers below that.
=> Make materia display logic more dynamic

packages/core/src/sims/cycle_sim.ts, packages/core/src/sims/sim_types.ts, packages/core/src/sims/sim_utils.ts, packages/core/src/test/test_utils.ts, packages/frontend/src/scripts/sims/healer/ast_sheet_sim.ts, packages/frontend/src/scripts/sims/healer/sch_sheet_sim.ts, packages/frontend/src/scripts/sims/healer/whm_new_sheet_sim.ts, packages/frontend/src/scripts/sims/melee/nin/nin_gauge.ts, packages/frontend/src/scripts/sims/melee/nin/nin_lv100_sim.ts, packages/frontend/src/scripts/sims/melee/rpr/rpr_gauge.ts, packages/frontend/src/scripts/sims/melee/rpr/rpr_sheet_sim.ts, packages/frontend/src/scripts/sims/melee/sam/sam_gauge.ts, packages/frontend/src/scripts/sims/melee/sam/sam_lv100_sim.ts, packages/frontend/src/scripts/sims/melee/vpr/vpr_gauge.ts, packages/frontend/src/scripts/sims/melee/vpr/vpr_sheet_sim.ts, packages/frontend/src/scripts/sims/sim_processors.ts
Splits up the rotation-generating step and the calculating-damage step of `BaseMultiCycleSim` and `CycleProcessor`.
`BaseMultiCycleSim` now caches the most recent rotation and only re-generates it when speed stat changes, instead of generating the rotation with every call to `simulate()
=> Split rotations and damage new

.idea/inspectionProfiles/Project_Default.xml, packages/backend-resolver/src/server_builder.ts, packages/common-ui/styles/common.less, packages/core/src/gear.ts, packages/core/src/sheet.ts, packages/frontend/src/scripts/components/items.ts
When there are items that could be replaced by another item and provide a pure upgrade or exact same stats, this will be indicated on the UI:
Clicking the button opens this dialog:
=> Show equivalent alt items

packages/frontend/src/scripts/components/stat_tier_display.ts
An accidental "this" appears in stat_tier_display.ts, which overrides the main stat tier div instead of the expansion DIVs
This is inside the loop that generates the different remove/add materia variations for the stat tiers
It causes 2 issues:
1. The popup info for the lowerLeftDiv is wrong
2. There's no popup info for the any of the expansion lowerLeftDivs
Removing the "this" fixes both of those issues
=> Fix the mouseover info in the stat tier display

packages/frontend/src/scripts/components/sheet.ts
Just a little typo
Before:
After:
=> Fix Error! appearing for Separator descriptions

packages/common-ui/styles/common.less, packages/frontend/src/scripts/components/items.ts
1. Make input colors consistent on toolbar
2. Fix the width of the alt-items modal (it has enough width to fit the final column on one row)
=> Cosmetic fixes

packages/core/src/sims/cycle_settings.ts, packages/core/src/sims/cycle_sim.ts, packages/core/src/sims/melee/nin/nin_lv100_sim.ts, packages/core/src/sims/melee/sam/sam_lv100_sim.ts, packages/core/src/sims/processors/sim_processors.ts, packages/core/src/test/sims/combo_test.ts, packages/core/src/test/sims/cycle_processor_tests.ts
Implements four cutoff modes:
1. 'prorate-gcd' is the previous default behavior. The final GCD will have its damage prorated based on how much of it fit into the fight time.
2. 'prorate-application' is like 'prorate-gcd', but will use the application time rather than the GCD time.
3. 'lax-gcd' allows the final GCD to fit in its entirely, but uses the start of the next GCD as the time basis for calculating DPS, i.e. if the fight time is 120, but your last GCD comes back up at 121.5, then the DPS will be (damage / 121.5) rather than (damage / 120).
4. 'strict-gcd' works like 'lax-gcd', but drops incomplete GCDs entirely and uses the time of the last GCD that you could start, but not finish, within the timestamp. There is one sort-of exception - if a GCD's entire recast period would fit, but …
=> Implement logic for different fight cutoff modes

packages/core/src/sims/tank/drk/drk_actions.ts, packages/core/src/sims/tank/drk/drk_lv100_sim.ts, packages/core/src/sims/tank/drk/drk_types.ts, packages/core/src/sims/tank/drk/rotations/drk_lv100_246.ts, packages/core/src/sims/tank/drk/rotations/drk_lv100_250.ts
Living Shadow now works correctly:
- Damage is applied when it should be applied
- Darkside no longer applies
- It still needs to get the correct stats, but that will come later, as it requires a deeper change
Prepull TBN is added
Some extra pre-work has been done in advance of adding the computationally created rotation
=> [DRK Sim] Improve Living Shadow, add Prepull TBN, misc improvements/fixes

packages/core/src/solving/gearset_generation.ts, packages/frontend/src/scripts/components/meld_solver_modal.ts, packages/frontend/src/scripts/workers/meld_generation_worker.ts
Fixed:
- target gcd text box being disabled wrong
- meld solver not including relic stats in generated sets
Added:
- auto-fills the current GCD of the set for the target GCD
=> More feexes

packages/core/src/datamanager_new.ts, packages/core/src/test/datamanager_tests.ts
Addresses #359 
I will double check if this is appropriate based on in-game instances tomorrow, but I believe this is correct behavior. l94/i663 items lose their melds in game so I believe l94/i660 should as well.
=> Prevent melds on items based on equip level

packages/core/src/sheet.ts, packages/frontend/src/scripts/components/sheet.ts
Instead of always placing cloned sets at the bottom, they will now be placed immediately prior to the next separator if one exists. Since separators are typically used to delineate categories or sections, this keeps cloned sets in the same logical section.
Fixes #362
=> Place cloned sets prior to the next separator

packages/core/src/sims/cycle_sim.ts, packages/core/src/sims/sim_types.ts, packages/core/src/sims/tank/drk/drk_actions.ts, packages/core/src/sims/tank/drk/drk_sheet_sim.ts, packages/core/src/sims/tank/drk/drk_types.ts
This adds a framework for abilities being different at different levels, and adds support for level 70 + 80 + 90 DRK. It all seems to work! There's no overcap, even for e.g. 2.40 at level 70.
In reworking the way burst worked to no longer reference Living Shadow, I also found a minor optimization for level 100 2.50.
=> Level 70 + 80 + 90 DRK and level-based ability modification

packages/frontend/src/index.html
Fix missing crossorigin attribute on preloads
Without the `crossorigin` attribute, preloads don't actually work.
=> Fix preloads

packages/backend-resolver/src/server_builder.ts, packages/backend-resolver/src/test/test_endpoints.ts, packages/core/src/external/shortlink_server.ts, packages/core/src/external/static_bis.ts
- Fixes server-side preloads not including the `crossorigin` attribute
- Include API URL preload for saved sheets and bis
- Adds tests for server-side preloads
=> Improve server side preloads

packages/frontend/src/scripts/components/sheet.ts
Preamble: I understand that as with any UX thing, differing opinions exist. As a result, if this is something you don't feel is an improvement, feel free to close this. However, I do believe this makes things better.
Today, gearsets are gradiented based on the difference between the worst and the best. This means that two very similar sets will show 'unfavourable red' even if they are very close. It also means that adding a new set affects the gradients of the others. See examples:
This approach instead uses a gradient based a logarithm so that the further away from best it is, the more it leans towards unfavourable. Anything 5% worse is always considered red. I'm not attached to this logarithm base (I think it could be even lower, but it seemed a good default).
See examples here:
=> Update set sim results gradiants to not be relative to the worst set

packages/core/src/sims/melee/rpr/rpr_sheet_sim.ts
It seems like when the linter started enforcing strict checks the checks were rewritten as `!== null` when it should've been `!== undefined`.
=> Fix RPR gauge update conditionals #394

packages/common-ui/styles/common.less, packages/frontend/src/scripts/components/items.ts, packages/xivmath/src/xivconstants.ts
Current prod:
Fixed:
This probably got broken when I added the "unequip item" button.
=> Fix item name width not shrinking correctly

packages/core/src/sims/healer/ast_sheet_sim.ts
This logic was implemented in the rpr and monk sims to make sure that oGCDs that came up during spin time don't drift. By using it in the 2 minute burst function astro won't end up casting star 7-8s early at the end of the sim.
=> Fix ast sim drifting star and using in burst when it can't be used

packages/backend-resolver/src/server_builder.ts, packages/core/src/nav/common_nav.ts, packages/frontend/src/scripts/components/export_controller.ts
Fix issue that would cause some URLs to not work, if they fell below the URL query-based limit and did not need to fall back to URL hash.
Example of broken link: https://xivgear.app/?page=viewset%7C%257B%2522name%2522%253A%2522Default%2520Set%2520copy%2522%252C%2522sets%2522%253A%255B%257B%2522name%2522%253A%2522Default%2520Set%2522%252C%2522items%2522%253A%257B%2522Weapon%2522%253A%257B%2522id%2522%253A43103%252C%2522materia%2522%253A%255B%257B%2522id%2522%253A-1%257D%252C%257B%2522id%2522%253A-1%257D%255D%257D%257D%252C%2522isSeparator%2522%253Afalse%252C%2522relicStatMemory%2522%253A%257B%257D%252C%2522materiaMemory%2522%253A%257B%257D%257D%255D%252C%2522level%2522%253A100%252C%2522job%2522%253A%2522WAR%2522%252C%2522partyBonus%2522%253A0%252C%2522sims%2522%253A%255B%255D%252C%2522itemD …
=> Fix a bug with URL encoding

packages/core/src/sims/processors/sim_processors.ts, packages/core/src/util/array_utils.ts, packages/frontend/src/scripts/base_ui.ts, packages/frontend/src/scripts/components/ads.ts, packages/frontend/src/scripts/nav_hash.ts, packages/math-frontend/src/scripts/base_ui.ts, packages/math-frontend/src/scripts/nav_hash.ts
This allows for an array cache key instead of a single value. It also allows sub-classes to override the cache key, for if there are sim-specific tweaks where the cache should be invalidated.
Closes #422
=> Fix sim caching

packages/common-ui/src/components/util.ts, packages/frontend/src/scripts/components/materia.ts, packages/frontend/src/scripts/components/meld_solver_modal.ts
Meld solver now defaults to target GCD being toggled as true, and displays the number to two decimal places (i.e. `2.50` instead of `2.5`.
After:
=> Default meld solver to current GCD, small UX tweaks

packages/core/src/sims/melee/mnk/mnk_sim.ts
Forgot to enable this by default in the big PR.
=> Toggle MNK sim to default

packages/core/src/sims/melee/mnk/mnk_sim.ts
Because monk has a probabilistic chakra generation, the rotation changes due to crit chance. Preserving crit chance at the same GCD tier leads to inaccurate DPS estimates. This means monk sim doesn't get to use the cache behavior much at all.
Closes #437
=> Bust monk rotation cache using crit chance

packages/core/src/sims/caster/pct/pct_actions.ts, packages/core/src/sims/caster/pct/pct_buffs.ts, packages/core/src/sims/caster/pct/pct_consts.ts, packages/core/src/sims/caster/pct/pct_gauge.ts, packages/core/src/sims/caster/pct/pct_types.ts
Add the skeleton for a Pictomancer simulator for https://github.com/xiv-gear-planner/gear-planner/issues/238.
Adds in:
* Actions
* All ST Spells
* All relevant oGCDs
* Initial logic for applying and removing buffs
* Skeleton Gauge with no frills
=> [PCT Sim] Add initial Picto consts, types, actions, buffs, and a primitive gauge.

packages/common-ui/src/components/gauges.ts, packages/common-ui/styles/common.less, packages/common-ui/styles/gauge.less, packages/frontend/src/scripts/sims/melee/nin/nin_lvl100_sim_ui.ts, packages/frontend/src/scripts/sims/tank/pld_sheet_sim_ui.ts
Should look exactly the same as before, but now has a standalone class that can be used to implement this, rather than copy-pasting the same code into every sim gui.
This PR only updates PLD and NIN, the rest can be updated later.
=> Add generic gauge bar and change PLD+NIN to use it

packages/core/src/sims/melee/mnk/mnk_actions.ts
While talking with Hint, she expressed that it would be desirable to fix RoW auto timing no matter how, as inaccurate auto timing would favor higher SkS gearsets due to auto scaling.
This fix is mathematically valid, but obviously needs to be documented in case changes to haste calculations are done in the future.
`2.56 * (100 - 40 - 20) / 100 == 1.024`
=> Correct Riddle auto timing in a hacky way

packages/backend-resolver/src/server_builder.ts, packages/backend-resolver/src/test/test_endpoints.ts, packages/core/src/external/shortlink_server.ts, packages/core/src/nav/common_nav.ts, packages/core/src/test/common_nav_test.ts, packages/frontend/src/scripts/base_ui.ts, packages/frontend/src/scripts/components/export_controller.ts, packages/frontend/src/scripts/components/sheet.ts, packages/frontend/src/scripts/nav_hash.ts
Allows for full sheets to be filtered to a single set and opened as if they were a single set export. This will have some other benefits, like allowing the pop-out link on embedded sets to link back to a full sheet.
Closes #442
=> Sheet index url param

packages/common-ui/styles/common.less
=> Give toolbar drag indicators a tiny bit of breathing room

packages/core/src/sheet.ts, packages/core/src/test/export_import_tests.ts
Makes the default role bonus 5 for non-BLU jobs and 1 for BLU, to better be a (in my opinion) better and more expected default.
=> Make role bonus for new sheets 5 default (or 1 for BLU)

packages/common-ui/styles/common.less, packages/frontend/src/scripts/components/sheet.ts
If width <= 800px, only the name/description, sims, and GCD(s) will be shown by default:
"Toggle Details" will still show all the columns:
Also fixes a bug due to a leftover from an older version of the UI where you could hover/click through the semi-transparent backgrop of the buttons.
=> Implement more compact table view for narrow screens

packages/core/src/sims/tank/drk/drk_gauge.ts, packages/core/src/sims/tank/drk/drk_types.ts, packages/core/src/sims/tank/gnb/gnb_actions.ts, packages/core/src/sims/tank/gnb/gnb_gauge.ts, packages/core/src/sims/tank/gnb/gnb_sheet_sim.ts, packages/core/src/sims/tank/gnb/gnb_types.ts, packages/core/src/sims/tank/pld/pld_sheet_sim.ts, packages/core/src/sims/tank/war/war_gauge.ts, packages/core/src/sims/tank/war/war_types.ts, packages/frontend/src/scripts/sims/tank/gnb_sheet_sim_ui.ts, packages/frontend/src/scripts/sims/tank/pld_sheet_sim_ui.ts
This adds some missing optimizations for Gunbreaker, improving the sim at every speed.
including:
- Using Sonic Break earlier if the fight is ending sooner
- Making sure we get Hypervelocities in No Mercy if possible by using Lionheart as our last No Mercy GCD instead of Burst Strike, in places where that's applicable
Before:
After:
I also added a decimal point of precision to No Mercy and Fight or Flight.
This also adds support for level 90, 80, and 70 for Gunbreaker.
Level 90, 80, and 70 results (I used slightly lazy fully synced gear and Manderville relic for my own sanity instead of recreating all of the BiS). These use DSR/TEA/UWU scaling respectively.
It also only shows two cartridges in the UI when you only have two carts, e.g. this is level 80:
=> Improve GNB at 100, add support for 90, 80, 70

packages/backend-resolver/src/server_builder.ts, packages/backend-resolver/src/test/test_endpoints.ts, packages/core/src/nav/common_nav.ts
Adds onlySetIndex support, and also allows you to call `/fulldata/?page=xyz` with the exact same paths as you would on the client side to make the endpoint easier to use.
=> Improve /fulldata/ endpoint

packages/frontend/src/scripts/workers/worker_pool.ts
Improves meld solving speed on systems with > 4 cores (previous fixed worker pool size).
As an aside: Mocha is already pulling in [workerpool](https://www.npmjs.com/package/workerpool) as a dependency; it might have made more sense to use that instead of rolling our own implementation.
=> Set size of the worker pool based on number of logical processors available

eslint.config.js, packages/common-ui/src/components/util.ts, packages/common-ui/src/settings/persistent_settings.ts, packages/common-ui/src/settings/settings_modal.ts, packages/common-ui/styles/common.less, packages/core/src/sims/common/potency_ratio.ts, packages/core/src/sims/cycle_sim.ts, packages/core/src/sims/healer/healer_mp.ts, packages/core/src/sims/healer/sge_sheet_sim.ts, packages/core/src/sims/healer/whm_sheet_sim.ts, packages/core/src/sims/processors/count_sim.ts, packages/core/src/sims/processors/sim_processors.ts, packages/core/src/sims/sim_types.ts, packages/core/src/sims/sim_utils.ts, packages/core/src/solving/gearset_generation.ts, packages/core/src/solving/sim_runner.ts, packages/frontend/src/scripts/base_ui.ts, packages/frontend/src/scripts/components/meld_solver_modal.ts, packages/frontend/src/scripts/components/meldsolver.ts, packages/frontend/src/scripts/workers/meld_generation_worker.ts, packages/frontend/src/scripts/workers/ping_worker.ts, packages/frontend/src/scripts/workers/simulation_worker.ts, packages/frontend/src/scripts/workers/worker_common.ts, packages/frontend/src/scripts/workers/worker_main.ts, packages/frontend/src/scripts/workers/worker_pool.ts
- Refactors worker pool.
- Only one worker is created by default. The rest are spun up as needed.
- Adds a secondary "simulateSimple" method to sims to provide a lighter-weight code path for when you do not care about anything other than the singular final DPS number (e.g. meld solving)
- Display total number of sets in solver modal
- Adds a "Ping worker" and some console debug things to allow you to check if the worker pool is functional
- Reconfigures `@typescript-eslint/no-unused-vars` to allow `_` to be used as an unused variable name.
=> Refactor meld solver workers

package-lock.json, package.json, packages/frontend/src/scripts/components/sheet.ts
This will always show level in the sync info if the item level is synced. Mostly, this helps prevents silly mistakes like forgetting to sync level and makes everything a lot more explicit, so I think this is generally a positive improvement. I think future work would include making 'strange' syncs' warn users, but I think this is a positive even in that world.
(Works in view mode too)
`tsconfig-paths-webpack-plugin` seems to be required to build, and it wasn't present in a package.json (npm install didn't install it) so I added it.
=> Always show level in sync info it item level is synced

packages/core/src/sims/melee/mnk/mnk_actions.ts
Wind's Reply
Potency has been increased from 900 to 1,040.
Reduction in potency after the first target has been changed from 50% to 40%.
Fire's Reply
Potency has been increased from 1,200 to 1,400.
Reduction in potency after the first target has been changed from 50% to 40%.
=> Add monk 7.2 potency bumps

packages/core/src/sims/melee/mnk/mnk_sim.ts
Because the sim needs to inspect the buffs recorded on each ability that is used, the `simpleMode` CycleProcessor cannot be used or the meld solver may generate the incorrect result in some cases.
Without the buffs, we can't estimate chakra gain properly, and so the meld solver's simmed DPS will differ wildly from the full simulation's DPS.
=> Have MNK sim run full simulation when simulateSimple is called

packages/core/src/sims/tank/gnb/gnb_sheet_sim.ts, packages/frontend/src/scripts/sims/tank/gnb_sheet_sim_ui.ts
The current sim will microclip (as expected) for Gunbreaker, i.e. intentionally clip its GCD due to the weird scaling of Gnashing Fang. This isn't 'incorrect' per se, because gaining more of a GCD is better in a vacuum, but the killtime dependency means that, practically, comparing sets at different speeds means the sim results show more value in SkS melds than it probably should.
This might feel like a bit of an ugly solution, but to me it feels like the right one (I first tried the opposite approach, being pessimistic and making all microclips as bad as possible). Due to the fact that FPS/ping/etc exists, this more closely matches the reality of playing the job (i.e. 2.50's fps/ping tax is just raw clipping whereas 2.45s will eat into the microclip and not be as bad as the sim shows), …
=> Add new default-on option to ignore Gunbreaker Gnashing Fang microclips

packages/frontend/src/scripts/base_ui.ts, packages/frontend/src/scripts/components/sheet.ts, packages/frontend/src/scripts/embed.ts
`openNormalBacklink` when you click the link to go back to the full sheet when viewing an onlySetIndex link.
`openEmbedToFull` is the same but when you're looking at an embed.
`displayEmbedError` is whenever the function `displayEmbedError()` is called.
`nonEmbeddedIframe` is fired when using a non-embedded UI in an iframe.
`iframe` is fired whenever the page is in an iframe.
#1 does not work for non-iframes because the page navigation immediately cancels the request. This should be fixed, but is out of scope for this. It works in iframes because the link is set to open in a new tab.
=> Add more things for analytics

packages/frontend/src/scripts/components/sheet.ts
This makes it so that clicking the backlink on an `onlySetIndex` URL will not try to completely reload the page.
=> Fix backlink click completely reloading the page

packages/common-ui/styles/common.less, packages/core/src/gear.ts, packages/core/src/sheet.ts, packages/core/src/solving/gearset_generation.ts, packages/core/src/test/materia_memory_test.ts, packages/frontend/src/scripts/components/materia.ts, packages/frontend/src/scripts/components/meld_solver_modal.ts, packages/frontend/src/scripts/components/sheet.ts, packages/xivmath/src/geartypes.ts
Closes #507, #499, #348 (effectively)
=> Materia improvements

packages/backend-resolver/src/server_builder.ts, packages/core/src/external/static_bis.ts, packages/core/src/imports/imports.ts, packages/core/src/nav/common_nav.ts, packages/core/src/test/common_nav_test.ts, packages/frontend/src/scripts/nav_hash.ts
This PR does two things:
- Renames 'expac' to 'folder' for static bis sets
- Allows static BiS sets to not require a folder, e.g. `bis/drk/set` will be permissable, as well as `bis/drk/foo/set`
It works:
=> Add the ability to specify a single-folder BiS link

packages/frontend/src/scripts/components/sheet.ts
Still probably not a good idea to have a blank separator since the user clicks on it and there's nothing to see which is probably more confusing, but now you can.
=> Fix the blank separator bug #506

packages/frontend/src/scripts/components/gear_edit_toolbar.ts, packages/frontend/src/scripts/components/materia.ts, packages/frontend/src/scripts/components/sheet.ts
There are a few problems with including the meld solver in the fill/lock button in my eyes:
- Users get confused that the fill priority affects the meld solver
- This is one of the most awesome features of the site, and hiding it in a sub-menu can cause people to not know about it
This PR makes the meld solver button first-class, and moves it out of the fill/lock button. Making it more obviously disconnected from the 'fill' capabilities, as well as being more obvious to users.
=> Make Meld Solver button first-class, rename materia fill/solve to materia fill/lock

packages/common-ui/src/table/tables.ts, packages/common-ui/styles/common.less, packages/frontend/src/scripts/sims/components/ability_used_table.ts, packages/frontend/src/scripts/sims/count_sim_gui.ts, packages/frontend/src/scripts/sims/multicyclesim_ui.ts
Possible future PRs:
- Allow enabling/disabling specific rotations on the cycle sim config page
=> Improve cycle sim result display

packages/util/src/array_utils.ts
Fixes #483 
Should not affect anything since the only rotations this would remove would be non-viable, like redotting at 2 seconds.
=> fix range/rangeInc ignoring start number

packages/core/src/sims/tank/war/war_types.ts
50267 isn't a real ID, correcting it to 1897 (what it should be). See also: https://www.garlandtools.org/db/#status/1897
=> Fix Nascent Chaos status ID

packages/common-ui/src/components/util.ts, packages/frontend/src/scripts/components/custom_item_manager.ts, packages/frontend/src/scripts/components/materia.ts, packages/frontend/src/scripts/components/meld_solver_modal.ts, packages/frontend/src/scripts/sims/components/cycle_settings_components.ts, packages/frontend/src/scripts/sims/components/result_settings.ts
Closes #538 
This also makes `inputMode: decimal` the default for `FieldBoundFloatField`, and makes `inputMode: number` plus an appropriate `pattern` attribute the defaults for `FieldBoundIntField` and variants.
=> Configure input types and patterns so that you get the numeric keypad on iOS

packages/core/src/sims/tank/gnb/gnb_sheet_sim.ts
Specifically does this for 2.50, whereas previously it'd use Brutal Shell. Minor gain to 2.50 DPS, other speeds untouched.
=> [GNB Sim] Add hypervelocity no mercy optimization for 2.50

packages/xivmath/src/xivconstants.ts
Also changes to use the same default food item level at each level sync bracket.
=> Change food item level default to 740

.idea/inspectionProfiles/Project_Default.xml, packages/common-ui/styles/common.less, packages/frontend/src/scripts/components/sheet.ts
- Adds missing button shadow
- Replaces title with `<No Name>` if there is no name specified.
=> Improve separator editor styling

packages/backend-resolver/src/server_builder.ts, packages/core/src/external/static_bis.ts, packages/core/src/imports/imports.ts, packages/core/src/nav/common_nav.ts, packages/core/src/test/common_nav_test.ts, packages/frontend/src/scripts/components/import_sheet.ts, packages/frontend/src/scripts/components/sheet.ts, packages/frontend/src/scripts/nav_hash.ts
- Changes getBisSheet/getBisSheetFetchUrl to accept a single `path: string[]` argument instead of the old-style.
- Make embedding work correctly with BiS links
- Fix importing for new BiS paths
- Fix a few missing error cases
Fixes https://github.com/xiv-gear-planner/static-bis-sets/issues/9
=> Fix BiS link embeds and improve new bis paths

.github/workflows/frontend_docker.yml, package.json, packages/backend-resolver/package.json, packages/common-ui/package.json, packages/core/package.json, packages/data-api-client/package.json, packages/frontend/package.json, packages/frontend/webpack.config.js, packages/i18n/package.json, packages/math-frontend/package.json, packages/util/package.json, packages/xivmath/package.json
Turns minimization (back) on, without breaking anything (hopefully).
- `chunkIds: 'named',` retains the deterministic filenames so that the webworker script has a fixed filename
- `devtool: 'source-map',` retains working source maps alongside minimized JS, without packing the source map into the JS
=> Minify JS without breaking webworker

packages/common-ui/styles/common.less, packages/frontend/src/scripts/components/materia.ts, packages/frontend/src/scripts/components/meld_solver_modal.ts, packages/frontend/src/scripts/components/sheet.ts, packages/frontend/src/style.less
- Improves the solver results dialog. Layout same except for moving the delta column to the middle, under the arrow. Internally, it uses a CSS flex grid to make sure things stay aligned even if cell heights vary due to text wrapping.
- Display an alert if the user attempts to open the meld solve dialog when the sheet has no sims, rather than silently failing.
- The materia totals is collapsed by default and expands after being clicked (might revert or rethink this)
=> Improve solver results, fix a bug, and change meld totals

packages/common-ui/src/components/modal.ts, packages/common-ui/src/modalcontrol.ts, packages/frontend/src/scripts/components/materia.ts, packages/frontend/src/scripts/components/meld_solver_modal.ts
- Modals can now opt-out of being closed if you click the background area (fixes #373 )
- Removed some dead code in the meld solver dialog
=> Ability to block dialog click-off, some cleanup

packages/core/src/sims/melee/mnk/mnk_sim.ts
While implementing the triple lunar rotation I noticed that the 8 minute burst window entry was incorrect in all rotations due to drift / GCD alignment. This caused all rotations to desync brotherhood and rof double weaves while entering the 8 minute window, because the blitz entry logic was not considering windows that would allow the first GCD under buffs to be a blitz.
=> Fix blitz window entry for "-3" opos

packages/core/src/sims/melee/mnk/mnk_sim.ts, packages/core/src/sims/melee/mnk/mnk_types.ts
Another rotation for long encounters. Now that rotations can be selected by the end user I thought it would be valuable to have the 3rd monk rotation displayed. Previously I didn't think it was worth including as if it simmed the highest it would not be representative of "average play".
=> Implement the triple lunar rotation

packages/common-ui/src/components/show_hide_chevron.ts, packages/core/src/gear.ts, packages/frontend/src/scripts/components/items.ts, packages/frontend/src/scripts/components/sheet.ts
Fixes #474 
If you double-click a show/hide thing for a gear slot instead of single-clicking, it will show/hide every gear slot at once.
=> Double click a row to hide all slots

packages/common-ui/styles/common.less, packages/frontend/src/scripts/components/stat_tier_display.ts
Fixes the stat displays on very narrow screens.
This also introduces a new "shortLabel" optional property which allows tiering labels to be even shorter, e.g. "SpS DoT" -> just "DoT".
=> Improve stat tier display on narrow screens

packages/common-ui/src/components/util.ts, packages/core/src/customgear/custom_item.ts, packages/core/src/sheet.ts, packages/core/src/test/custom_items_test.ts, packages/frontend/src/scripts/components/custom_item_manager.ts
Fixes #492 
Makes two improvements:
- Autocomplete will suggest values for stats
- For main stats, it will suggest the cap
- For substats, it will suggest the cap, 70% of the cap (the secondary substat), and zero
- Items will default to the highest ilvl item available for that stat, rather than the minimum ilvl for the level
=> Custom item UI improvements

packages/frontend/src/scripts/components/sheet.ts
As per title. Makes sense for them to be consistent and it is the most salient piece of info in both.
=> Make sim info consistent in both view and edit mode by moving it to the left in edit mode

.idea/inspectionProfiles/Project_Default.xml, packages/common-ui/styles/common.less, packages/frontend/src/scripts/components/bis_browser.ts, packages/frontend/src/scripts/components/items.ts, packages/frontend/src/scripts/components/job_icon.ts, packages/frontend/src/scripts/components/new_sheet_form.ts, packages/frontend/src/scripts/components/saved_sheet_picker.ts, packages/frontend/src/scripts/components/sheet.ts, packages/xivmath/src/xivconstants.ts
=> Add job icons to saved sheet picker

packages/core/src/customgear/custom_item.ts, packages/core/src/datamanager.ts, packages/core/src/datamanager_new.ts, packages/core/src/gear.ts, packages/core/src/sheet.ts, packages/core/src/test/custom_items_test.ts, packages/core/src/test/datamanager_tests.ts, packages/core/src/test/export_import_tests.ts, packages/core/src/test/sims/sim_tests.ts, packages/core/src/test/stats/auto_crit_dh_tests.ts, packages/core/src/test/stats/general_stats_tests.ts, packages/data-api-client/src/dataapi.ts, packages/frontend/src/scripts/components/new_sheet_form.ts, packages/frontend/src/scripts/components/sheet.ts, packages/frontend/src/scripts/nav_hash.ts, packages/frontend/src/scripts/workers/worker_main.ts, packages/math-frontend/src/scripts/mathpage/formulae.ts, packages/xivmath/src/geartypes.ts, packages/xivmath/src/xivconstants.ts
Closes #272 and #587
This allows you to have a role-based sheet, which includes jobs of all roles. The sheet still has a "primary" job as selected on the new sheet (or the "save as" screen), but you can change the job for an individual set within the sheet.
=> Multi-job sheets

packages/core/src/sheet.ts, packages/frontend/src/scripts/components/new_sheet_form.ts
Remove job overrides from all sheets when converting from multi-job to single-job.
=> Fix save-as behavior for multi-job to single-job sheet

packages/common-ui/src/table/tables.ts, packages/common-ui/styles/common.less, packages/frontend/src/scripts/components/bis_browser.ts
Overlays a real `<a>` element over the bis browser links so that you can middle click/open in new tab.
Fixes #588
=> Add real links to bis browser

packages/core/src/sims/healer/ast_sheet_sim.ts, packages/core/src/sims/sim_types.ts
You can now wrap any `Ability`-ish type with `LevelModifiable<X>` to allow `levelModifiers` to contain your type's custom fields.
=> Improve level modifiers to make them respect unique fields on different ability types

packages/core/src/sims/tank/gnb/gnb_sheet_sim.ts
This makes the solution a lot more elegant. In essence, we will subtract from the cooldown the difference between the ideal cooldown and the actual cooldown. It also no longer cheats.
Additionally this fixes a bug introduced by https://github.com/xiv-gear-planner/gear-planner/pull/544 that caused issues in the 1m for speeds other than 2.50
=> [GNB] Fix logic error with gnb microclip setting, make it work in a more intuitive way

packages/core/src/sims/buff_helpers.ts, packages/core/src/sims/melee/mnk/mnk_actions.ts, packages/core/src/sims/melee/vpr/vpr_buffs.ts, packages/core/src/sims/sim_types.ts, packages/core/src/sims/tank/drk/drk_gauge.ts, packages/core/src/test/sims/common_values.ts, packages/core/src/test/sims/cycle_processor_tests.ts, packages/core/src/test/stats/auto_crit_dh_tests.ts, packages/core/src/test/stats/buff_helpers_tests.ts, packages/frontend/src/scripts/sims/components/buff_list_display.ts
Status effects now require an ID. Negative numbers can be used to indicate that the ID is fake, and no Xivapi lookup should be performed. The `noStatusId()` function can be used to assign a unique negative ID.
=> Make status ID required, implement helper

packages/common-ui/src/table/tables.ts, packages/common-ui/styles/common.less, packages/core/src/gear.ts, packages/core/src/sheet.ts, packages/frontend/src/scripts/components/items.ts, packages/frontend/src/scripts/components/relic_stats.ts, packages/frontend/src/scripts/components/sheet.ts, packages/frontend/src/style.less
While in the code, I also made a small change to make relics which are unequipped display a '-' instead of a '0' in stats that the relic in question does not support.
=> Fixes some regressions with custom-stat relics

packages/frontend/src/scripts/components/stat_tier_display.ts, packages/xivmath/src/xivstats.ts
When lookin at predicted/extended tiering (i.e. tiering plus or minus a certain amount of materia), this will now reflect the tiering as if you were to actually equip the item, rather than just adding the raw amount that the materia would provide. This provides a more realistic picture when you have food with an uncapped stat.
Fixes #606
=> First attempt at improving predictive tiering

packages/core/src/gear.ts, packages/core/src/sims/sim_utils.ts, packages/core/src/test/sims/common_values.ts, packages/core/src/test/sims/cycle_processor_tests.ts, packages/core/src/test/stats/auto_crit_dh_tests.ts, packages/core/src/test/stats/general_stats_tests.ts, packages/xivmath/src/geartypes.ts, packages/xivmath/src/xivmath.ts, packages/xivmath/src/xivstats.ts
The old one was 'correct' by accident at level 100 because 440 * 1.05 = 462 which is suspiciously similar to +22. tl;dr:
- Living Shadow was 2 strength off at level 100
- It was incorrect by I can't be bothered to figure it out at 90 and 80
Correct value is ⌊440 * 1.00⌋ + 2, and correct base for player is ⌊440 * 1.05⌋ + RacialOffset
I also feel like the code was messy/bad so I cleaned it up a bit. No reason to re-get racial stats when they're right there. This also should help us better split up gear stats and non-gear stats if we ever need to in the future, also.
=> [DRK] Correct Living Shadow scaling, make the code better

packages/core/src/sims/melee/mnk/mnk_actions.ts
- Fix the potency of coeurl fury as it applies to snap punch
- Fix furies not applying to their relative GCDs whatsoever
- Add fake statusIds to work around fake buff overwriting #613
=> Fix monk fury stack application

packages/core/src/sims/melee/mnk/mnk_actions.ts, packages/core/src/sims/melee/mnk/mnk_sim.ts, packages/core/src/sims/melee/mnk/mnk_types.ts
This copies the only differences from the new abilities monk gains from 91-100 to the basic GCDs that they are upgrades for.
I checked that this behaves identical to live for level 100 using the MNK bis sheet and the opener looks good at 90, however without published resources for 90 openers it's a best effort.
=> Add level 80 and 90 monk support by updating potencies and openers

package.json, packages/backend-resolver/src/server.ts, packages/common-ui/src/components/util.ts, packages/core/src/data_api_client.ts, packages/core/src/datamanager_new.ts, packages/core/src/external/xivapi.ts, packages/core/src/sims/sim_types.ts, packages/data-api-client/src/dataapi.ts, packages/frontend/src/scripts/components/abilities.ts, packages/frontend/src/scripts/components/job_name_translator.ts, packages/frontend/src/scripts/components/saved_sheet_picker.ts, packages/frontend/src/scripts/components/sheet.ts, packages/frontend/src/scripts/components/stat_tier_display.ts, packages/frontend/src/scripts/components/status_effects.ts, packages/frontend/src/scripts/sims/components/ability_used_table.ts, packages/frontend/src/scripts/sims/components/buff_list_display.ts, packages/frontend/src/scripts/sims/party_comp_settings.ts, packages/i18n/src/translation.ts
Closes #332 
Out of scope:
- Base Params: These are always referred to by abbreviations rather than full names, and there do not seem to be any official abbreviations
- Races: For now, this is blocked until I fix a couple of the names not matching exactly what is in the data files
- Text-only buff labels: This is typically only done for "fake buffs" so we wouldn't be looking them up in xivapi anyway.
=> More translation

.github/workflows/backend_docker.yml, .github/workflows/frontend_docker.yml, .github/workflows/lint_only.yml, .github/workflows/math_frontend_docker.yml, .github/workflows/test_only.yml
This will cause obsolete workflows (i.e. those which are still running when a new commit has been added to the branch or PR in question) to be canceled.
=> Add concurrency controls to github actions

packages/common-ui/src/components/modal.ts, packages/core/src/gear.ts, packages/core/src/sheet.ts, packages/core/src/test/custom_items_test.ts, packages/frontend/src/scripts/components/custom_item_manager.ts, packages/frontend/src/scripts/components/sheet.ts
- Fix custom items not refreshing if the modal was closed by means other than the close button
- You can now safely delete custom items when they are equipped. An extra confirmation will pop up. If you answer yes, it will remove the item from all sets where it is equipped. If you answer no, the deletion will be canceled.
=> Custom item improvements

package-lock.json, packages/frontend/src/scripts/components/new_sheet_form.ts
Live:
Local:
Still adds 'copy' for exported sheets, or existing saved sheets
Exported:
Existing:
=> Don't add ' copy' to the name of newly imported sheets

packages/common-ui/styles/common.less, packages/frontend/src/scripts/components/sheet.ts
I also made the decision to move it to the front in edit mode too, so that it wouldn't move around.
Before:
After:
=> Always show level sync info on small screens

packages/core/src/sims/caster/blm/blm_actions.ts, packages/core/src/sims/caster/blm/blm_gauge.ts, packages/core/src/sims/caster/blm/blm_sheet_sim.ts, packages/core/src/sims/caster/blm/blm_types.ts, packages/frontend/src/scripts/sims/caster/blm_sim_ui.ts
Cleaned leftover comments/code from DRK sim
Updated to use the new gauge system instead of a custom gauge
Fixed Blizzard IV having a 3.5s cast time instead of the intended 2.0s cast time
Some notes, I changed the element from being a number between -3 and +3 to being its own type, but with the gauge system change I'm not sure this information is even needed anymore, but it can't hurt to keep it in there.
I added a counter of cooldown drift and GCD clips at the end of the timeline, mostly to sanity check. Still would really like to improve the way oGCD weaves are handled (because burst is a mess atm) but for now I think it's good enough.
Some GCD speeds also don't align properly / align weirdly to refresh Thunder on time due to Thunderhead, this is not handled well for now.
I also just …
=> Updated BLM sim

packages/common-ui/styles/common.less, packages/frontend/src/scripts/components/items.ts
This is my number one UX pain point with xivgear that I finally remembered to get around to fixing.
With the current validator, it prevents you from changing them in the 'wrong order', leaving the one you tried to initially change as an incorrect input (e.g. if you were trying to type 500, it might be left as 50), meaning you have to re-enter everything.
It's super common for me to want to change the minimum first, and it commonly prevents me and it's very very annoying.
I considered adding some other kind of warning, but I think that's kind of solved by the existing items message
=> Remove validation for item level filters

.idea/inspectionProfiles/Project_Default.xml, packages/common-ui/styles/common.less, packages/core/src/sheet.ts, packages/frontend/src/scripts/components/new_sheet_form.ts, packages/frontend/src/scripts/components/sheet.ts
Closes #727 
Creates an equivalent of the save-as dialog but modifies in place. It will reload the sheet since we need to invalidate all of the existing GearItems.
This UI can be accessed via "More Actions", *or* by clicking on the lvl/ilvl sync pill (it's a clickable button now).
The actual dialog uses the same UI as the "Save As" dialog.
=> Dialog for modifying sync info of an existing sheet

packages/core/src/sims/ability_helpers.ts, packages/core/src/sims/cycle_sim.ts, packages/core/src/sims/melee/drg/drg_actions.ts, packages/core/src/sims/sim_types.ts, packages/core/src/sims/tank/drk/drk_actions.ts, packages/core/src/sims/tank/drk/drk_sheet_sim.ts
Adds an optional `buffApplicationDelay` to abilities that, if specified, will take precedence over the ability's `appDelay` for the application of buffs.
=> Add optional buff application delay to actions

packages/backend-resolver/src/server_builder.ts, packages/common-ui/src/components/modal.ts, packages/frontend/src/scripts/components/export_controller.ts
closes #520
If in view only mode, export will not export set anew, but instead use existing URL.
This has been a pretty big point of confusion when using the site anecdotally, and causes many, many unnecessary exports.
Also adds a pretty huge QoL change of having instant exports (i.e. don't need to press "generate") for already-exported sets.
=> Return same URL if export in view only mode

.idea/inspectionProfiles/Project_Default.xml, packages/common-ui/styles/common.less, packages/core/src/customgear/custom_item.ts, packages/core/src/datamanager_new.ts, packages/core/src/nav/common_nav.ts, packages/core/src/test/sims/sim_tests.ts, packages/frontend/src/popout.less, packages/frontend/src/scripts/base_ui.ts, packages/frontend/src/scripts/components/gear_edit_toolbar.ts, packages/frontend/src/scripts/components/items.ts, packages/frontend/src/scripts/components/popout_editor.ts, packages/frontend/src/scripts/components/sheet.ts, packages/frontend/src/scripts/nav_hash.ts, packages/frontend/src/scripts/popout.ts, packages/frontend/src/style.less, packages/xivmath/src/geartypes.ts
Allow gear set editor (maybe later, also the viewer) to pop out to another window for a specific set, so that you can have multiple set editors on-screen at once.
TODO:
=> Editor popout
