src/scripts/datamanager.ts
src/scripts/external/xivapitypes.ts
src/scripts/gear.ts
src/scripts/geartypes.ts
src/scripts/sims/components/ability_used_table.ts
src/scripts/sims/cycle_settings.ts
src/scripts/sims/sim_processors.ts
src/scripts/sims/sim_types.ts
src/scripts/xivconstants.ts
src/scripts/xivmath.ts

Cycle sims will have auto-attacks automatically factored in.

WIP: Autoattack support

---

src/scripts/sims/common/swiftcast.ts
src/scripts/sims/components/ability_used_table.ts
src/scripts/sims/rpr_sheet_sim.ts
src/scripts/sims/sge_sheet_sim_mk2.ts
src/scripts/sims/sim_processors.ts
src/scripts/sims/sim_types.ts
src/scripts/xivconstants.ts

Fixes #42 and #43 
Additionally adds hover text to the time column in the abilities used table.

Bugfixes for cast times and application delay

---

src/scripts/sims/sim_processors.ts
src/scripts/sims/whm_new_sheet_sim.ts
src/scripts/test/sim_test_utils.ts
src/scripts/test/sim_tests.ts

- Fixes pre-pull timing being wrong if multiple non-damaging abilities are used pre-pull
- "Fixes" initial auto-attack timing with some caveats

Prepull fixes

---

src/scripts/sims/common/swiftcast.ts
src/scripts/sims/sim_processors.ts
src/scripts/sims/sim_types.ts
src/scripts/test/sim_test_utils.ts
src/scripts/test/sim_tests.ts
src/scripts/test/test_utils.ts

This adds support for buffs which modify an ability and/or consume themselves prior to initiating an action.

Swiftcast support

---

src/scripts/sims/sim_processors.ts
src/scripts/test/sim_tests.ts

Allow manual insertion of SpecialRecord
Known issue is that if you manually specify a time, it won't re-order the resulting list to accomodate.

Special record support

---

src/scripts/xivconstants.ts

fix typo in #78

---

src/scripts/components.ts
src/scripts/datamanager.ts
src/scripts/test/datamanager_tests.ts

Refactors DataManager, also splits it into interface and class.

Refactor datamanager

---

src/scripts/xivstats.ts

Fixes main stat display not respecting party bonus (does not affect DPS calcs)

Fix main stat display

---

src/scripts/sims/blu_common.ts
src/scripts/sims/blu_flame120.ts
src/scripts/sims/default_sims.ts

Implements a simulation for a BLU Mortal Flame rotation with burst windows every 120s.

Initial BLU Flame 120s implementation

---

src/scripts/sims/blu_breath60.ts
src/scripts/sims/blu_common.ts
src/scripts/sims/blu_flame120.ts
src/scripts/sims/default_sims.ts

Expects #84.
Implements a simulation for a BLU Breath of Magic rotation with burst windows every 60s.

Initial BLU Breath 60s implementation

---

src/scripts/sims/blu_winged60.ts
src/scripts/sims/default_sims.ts

Expects #84.
Implements a simulation for a BLU Winged Reprobation rotation with burst windows every 60s.

Initial BLU Winged 60s implementation

---

src/scripts/sims/blu_flame60.ts
src/scripts/sims/default_sims.ts

Expects #84.
Implements a simulation for a BLU Moral Flame rotation with burst windows every 60s.

Initial BLU Flame 60s implementation

---

src/scripts/sims/blu_free_trial.ts
src/scripts/sims/default_sims.ts

Expects #84.
Implements a simulation for a BLU Free Trial rotation with burst windows every 120s.

Initial BLU Free Trial sim implementation

---

packages/frontend/src/scripts/components.ts
packages/frontend/src/scripts/sims/common/potency_ratio.ts
packages/frontend/src/scripts/sims/healer/sge_sheet_sim.ts
packages/frontend/src/scripts/sims/healer/sge_sheet_sim_mk2.ts
packages/frontend/src/scripts/simulation.ts
packages/frontend/src/style.less

Add simulation description field and UI

---

.idea/inspectionProfiles/Project_Default.xml
packages/frontend/src/scripts/components/status_effects.ts
packages/frontend/src/scripts/external/xivapi.ts
packages/frontend/src/scripts/sims/blu/blu_breath60.ts
packages/frontend/src/scripts/sims/blu/blu_common.ts
packages/frontend/src/scripts/sims/blu/blu_flame120.ts
packages/frontend/src/scripts/sims/blu/blu_flame60.ts
packages/frontend/src/scripts/sims/blu/blu_free_trial.ts
packages/frontend/src/scripts/sims/blu/blu_winged120.ts
packages/frontend/src/scripts/sims/blu/blu_winged60.ts
packages/frontend/src/scripts/sims/common/swiftcast.ts
packages/frontend/src/scripts/sims/components/ability_used_table.ts
packages/frontend/src/scripts/sims/components/buff_list_display.ts
packages/frontend/src/scripts/sims/default_sims.ts
packages/frontend/src/scripts/sims/sim_processors.ts
packages/frontend/src/scripts/sims/sim_types.ts
packages/frontend/src/scripts/test/sims/cycle_processor_tests.ts
packages/frontend/src/scripts/test/xivapi_tests.ts

Adds simulator and buff descriptions and refactors for `isReady` and stacked buff support.  Expects #90, #91, #92.

BLU descriptions and stacked buff refactor

---

packages/frontend/src/scripts/main.ts

Add handler to prevent double click text selection

---

.idea/inspectionProfiles/Project_Default.xml
packages/frontend/src/scripts/components.ts
packages/frontend/src/scripts/components/import_sheet.ts
packages/frontend/src/scripts/components/new_sheet_form.ts
packages/frontend/src/scripts/components/saved_sheet_picker.ts
packages/frontend/src/scripts/components/section.ts
packages/frontend/src/scripts/gear.ts
packages/frontend/src/scripts/main.ts
packages/frontend/src/scripts/persistence/saved_sheets.ts
packages/frontend/src/scripts/sims/components/cycle_settings_components.ts
packages/frontend/src/scripts/sims/components/result_settings.ts
packages/frontend/src/scripts/sims/party_comp_settings.ts
packages/frontend/src/scripts/sims/sim_processors.ts
packages/frontend/src/style.less

Modernizes a few areas that were missed in the first path.

Modernize other areas of the UI

---

packages/core/src/gear.ts
packages/core/src/relicstats/relicstats.ts
packages/core/src/util/strutils.ts
packages/frontend/src/scripts/components/sheet.ts
packages/xivmath/src/geartypes.ts

Turn relic validation issues into actual gear set issues, other minor enhancements

---

packages/core/src/nav/common_nav.ts
packages/frontend/src/scripts/nav_hash.ts

Fix handling of very long URLs

---

packages/frontend/src/style.less

Apply modern styling to welcome message

---

packages/frontend/src/scripts/sims/melee/rpr_sheet_sim.ts

Fix RPR void/cross reaping not having fixed GCD

---

packages/frontend/src/scripts/components/sheet.ts

Fix embed link URL to use new style paths

---

packages/core/src/sims/ability_helpers.ts
packages/core/src/sims/cycle_sim.ts
packages/core/src/sims/sim_types.ts
packages/frontend/src/scripts/test/sims/cycle_processor_tests.ts

This was already stubbed out, now it allows you to override.

Implement custom application delay

---

.github/workflows/backend_docker.yml
packages/backend-resolver/Dockerfile

Fixes the stats server pipeline to not do an npm build in the pipeline, only to do the same build in the dockerfile.

Don't do an unnecessary build

---

packages/core/src/sims/buffs.ts
packages/frontend/src/scripts/test/sims/cycle_processor_tests.ts

Adjust buff durations and timings for DT

Dawntrail buff adjustments

---

packages/core/src/sims/cycle_sim.ts
packages/frontend/src/scripts/sims/healer/sge_sheet_sim_mk2.ts

- Potion support for Sage
- Adds dot clip rotation
- Optimizes rotations to not re-dot if there is not enough remaining fight duration to justify it
- Optimizes rotations to not hold phlegma if there is not enough fight time left.

Sage potion support and dot clip rotation, other improvements

---

packages/frontend/src/scripts/sims/healer/whm_new_sheet_sim.ts

Add PoM icon

---

.gitignore
packages/frontend/src/scripts/sims/default_sims.ts
packages/frontend/src/scripts/sims/tank/pld_sheet_sim.ts

Sim doesn't fully support sks (it doesn't apply to anything but dots/autos) -- no plans to support sks in the future

Added PLD sim

---

packages/frontend/src/scripts/sims/default_sims.ts
packages/frontend/src/scripts/sims/processors/count_sim.ts
packages/frontend/src/scripts/sims/tank/pld/pld_actions_no_sks.ts
packages/frontend/src/scripts/sims/tank/pld/pld_sheet_sim_no_sks.ts
packages/frontend/src/scripts/sims/tank/pld/pld_usage_sim_no_sks.ts
packages/xivmath/src/deviation.ts

Add PLD usage sim

---

packages/frontend/src/scripts/sims/components/ability_used_table.ts

Adds an asterisk and hover text to explain that autos have the delay modifier factored in

---

packages/core/src/sims/buff_helpers.ts
packages/core/src/sims/cycle_sim.ts
packages/core/src/sims/sim_types.ts
packages/core/src/test/buff_helpers_tests.ts
packages/frontend/src/scripts/sims/components/ability_used_table.ts

Fix applicability of buffs on start vs snapshot

---

packages/core/src/external/etro_import.ts

Fix etro import not having shield slot

---

packages/frontend/src/scripts/sims/melee/rpr/rpr_sheet_sim.ts

- simplified the logic pre-burst
- better CD checking for rpr gcds

Rpr support

---

.idea/inspectionProfiles/Project_Default.xml
packages/common-ui/styles/common.less
packages/core/src/sheet.ts
packages/frontend/src/scripts/components/new_sheet_form.ts
packages/frontend/src/scripts/components/sheet.ts

Save as dialog can now change level/class/ilvl sync

---

packages/math-frontend/src/scripts/mathpage/formulae.ts
packages/xivmath/src/geartypes.ts
packages/xivmath/src/xivmath.ts
packages/xivmath/src/xivstats.ts

Not currently displayed on UI except for math page.

Add formula for TNC damage reductoin

---

.idea/inspectionProfiles/Project_Default.xml
packages/common-ui/src/components/util.ts
packages/common-ui/styles/common.less
packages/core/src/gear.ts
packages/core/src/sheet.ts
packages/core/src/test/custom_items_test.ts
packages/frontend/src/scripts/components/custom_item_manager.ts
packages/frontend/src/scripts/components/dropdown_actions_menu.ts
packages/frontend/src/scripts/components/items.ts
packages/frontend/src/scripts/components/new_sheet_form.ts
packages/frontend/src/scripts/components/sheet.ts
packages/frontend/src/scripts/sims/components/cycle_settings_components.ts
packages/frontend/src/scripts/sims/healer/whm_sheet_sim.ts
packages/frontend/src/style.less
packages/xivmath/src/geartypes.ts

Custom item support

---

packages/frontend/src/scripts/sims/melee/rpr/rpr_buff.ts
packages/frontend/src/scripts/sims/melee/rpr/rpr_gauge.ts
packages/frontend/src/scripts/sims/melee/rpr/rpr_sheet_sim.ts
packages/frontend/src/scripts/sims/melee/rpr/rpr_types.ts

- Adjusted opener to reflect recent changes
- Added potion usage

Rpr opener/burst changes

---

packages/core/src/sims/buffs.ts

Update more buffs for 7.0

---

packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/export_controller.ts
packages/frontend/src/scripts/components/sheet.ts
packages/frontend/src/scripts/components/stat_tier_display.ts
packages/frontend/src/scripts/components/totals_display.ts
packages/xivmath/src/geartypes.ts

Main table:
Tiering:
Read-only table (compact):
Read-only table (detail):
Read-only set detail:
Embed:

TNC mitigation display/tiering

---

packages/xivmath/src/xivconstants.ts

Added gcdDisplayOverrides for SAM and VPR

Added gcdDisplayOverrides for SAM and VPR

---

packages/frontend/src/scripts/sims/melee/rpr/rpr_actions.ts
packages/frontend/src/scripts/sims/melee/rpr/rpr_sheet_sim.ts

- Reworked AC logic, was previously bad
- Fixed sim crashes (hopefully)
- Reworked pot logic to be better

Reworked AC & pot logic

---

packages/core/src/external/xivapi.ts

Fix 'next' field in xivapi responses

---

packages/core/src/gear.ts

Fix HQ item data

---

packages/core/src/datamanager.ts
packages/core/src/external/xivapi.ts

This seems to improve load times

Optimize xivapi item level querying

---

packages/frontend/src/scripts/components/sheet.ts

Select first row when viewing an exported sheet

---

packages/core/src/sims/buffs.ts

(properly squashed rebase)
Adding Starry Muse buff to list of Party Buffs while working on the rest of the sim.

Add Starry Muse buff to list of Party Buffs.

---

packages/core/src/datamanager.ts
packages/core/src/sims/buffs.ts
packages/frontend/src/scripts/sims/melee/nin/nin_buffs.ts
packages/frontend/src/scripts/sims/melee/nin/nin_gauge.ts
packages/frontend/src/scripts/sims/melee/nin/nin_lv100_sim.ts
packages/frontend/src/scripts/test/sims/cycle_processor_tests.ts

- Update buff duration of dokumori and kunai
- Update start time of dokumori
- Add console warnings for bad kazematoi usage

Ninja Adjustments

---

.idea/inspectionProfiles/Project_Default.xml
packages/core/src/customgear/custom_food.ts
packages/core/src/customgear/custom_item.ts
packages/core/src/gear.ts
packages/core/src/sheet.ts
packages/core/src/test/custom_items_test.ts
packages/frontend/src/scripts/components/custom_item_manager.ts
packages/frontend/src/scripts/components/items.ts
packages/frontend/src/scripts/components/sheet.ts
packages/frontend/src/scripts/tables.ts
packages/frontend/src/style.less
packages/xivmath/src/geartypes.ts

Add support for custom food

---

packages/frontend/src/scripts/sims/healer/sch_sheet_sim.ts

Dot refresh is now based on previous dot
Now shows when Dissipation and Aetherflow are used
Now lets you modify number of energy drains
Now checks dot clipping in the opener

Updated Scholar Sim

---

packages/core/src/gear.ts
packages/core/src/sheet.ts
packages/frontend/src/scripts/components/sheet.ts
packages/frontend/src/scripts/tables.ts
packages/xivmath/src/geartypes.ts

Allow the use of separators in the table

---

packages/frontend/src/scripts/components/export_controller.ts

Also refactors the export modal code
Closes #249

Add teamcraft integration

---

packages/common-ui/src/modalcontrol.ts
packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/stat_tier_display.ts

Display tiering after one or more materia added/removed

---

packages/frontend/src/scripts/components/export_controller.ts
packages/frontend/src/scripts/components/sheet.ts
packages/frontend/src/scripts/nav_hash.ts

Improve Exports

---

packages/frontend/src/scripts/sims/healer/ast_sheet_sim.ts
packages/frontend/src/scripts/sims/healer/sch_sheet_sim.ts
packages/frontend/src/scripts/sims/healer/whm_new_sheet_sim.ts

SCH will dump EDs and AST will dump Lord if the boss will die before the next burst window

Updated Healer Sims

---

packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/sheet.ts

Closes #256 (but actually fixes it this time hopefully)

Try to fix ios bug

---

packages/common-ui/styles/common.less

Fix ilvl text clipping

---

packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/items.ts

Closes #304 
I know it's not the most favored UI (same as item removal) but it works.

Add button to remove food

---

packages/backend-resolver/src/server_builder.ts

Cache control for previews and fulldata

---

packages/core/src/test/general_stats_tests.ts
packages/xivmath/src/xivmath.ts

Add more test scases and fix tank DoT calc order.

Fix tank DoT order

---

packages/frontend/src/scripts/components/sheet.ts
packages/frontend/src/scripts/components/totals_display.ts

Fix set toolbar not refreshing on view-only mode

---

packages/core/src/customgear/custom_item.ts
packages/core/src/datamanager_new.ts
packages/core/src/datamanager_xivapi.ts
packages/core/src/test/datamanager_tests.ts
packages/data-api-client/src/dataapi.ts
packages/frontend/src/scripts/components/items.ts
packages/xivmath/src/geartypes.ts
packages/xivmath/src/xivstats.ts

Fixes #317 pending discussion of a few corner cases.
Also adds the ilvl that an item is synced down to in the item's tooltip.

Implement logic to fix issues with equiplevel based syncing

---

packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/gear_edit_toolbar.ts

UI for undo feature

---

packages/frontend/src/scripts/sims/ranged/dnc_sim.ts

Updates the DNC sim for DT release
- updates potencies
- updated some usage logic
This is intended to reflect the calculations in the DNC gear planner

Update dnc sim

---

packages/core/src/sims/common/potion.ts
packages/core/src/sims/sim_utils.ts
packages/core/src/test/sims/cycle_processor_tests.ts
packages/xivmath/src/xivstats.ts

Fix potion stat modifications

---

packages/frontend/src/scripts/components/meld_solver_modal.ts
packages/frontend/src/scripts/components/meldsolver.ts
packages/frontend/src/scripts/workers/meld_generation_worker.ts
packages/frontend/src/scripts/workers/worker_main.ts
packages/frontend/src/scripts/workers/worker_pool.ts

Fixes:
- help text disappearing on cancel
- "properly" handles when there are no gearsets generated (more to come when result modal is implemented)

Some meld solver fixes

---

packages/xivmath/src/xivconstants.ts

Fixes bug report via Discord: https://discord.com/channels/277897135515762698/1295863271328452659/1296018057466216448
@Makar8000 please review

Only apply Enhanced Fuka at level >= 78

---

packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/meld_solver_modal.ts
packages/frontend/src/scripts/components/meldsolver.ts

Result dialog for meld solver!

Solve Result Dialog

---

packages/core/src/sims/tank/drk/drk_lv100_sim.ts

There was a scroll bar hiding some of the text that I didn't like. Easy enough fix.
Before:
After:

Fix minor text causing a scroll bar

---

.gitattributes

Ref: https://git-scm.com/docs/gitattributes#_effects

Normalize line endings on check-out/check-in

---

packages/frontend/src/scripts/base_ui.ts
packages/frontend/src/scripts/workers/simulation_worker.ts
packages/frontend/src/scripts/workers/worker_main.ts
packages/frontend/src/scripts/workers/worker_pool.ts

- Fixes #372 
- Add worker names
- Fix potential race condition

Various worker enhancements

---

packages/xivmath/src/deviation.ts
packages/xivmath/src/xivmath.ts

Looks like this is a leftover from the rounding refactor in #312

Remove extraneous floor()

---

packages/core/src/sims/default_sims.ts
packages/core/src/sims/tank/drk/drk_sheet_sim.ts
packages/core/src/sims/tank/drk/drk_types.ts
packages/frontend/src/scripts/sims/sim_guis.ts
packages/frontend/src/scripts/sims/tank/drk_sheet_sim_ui.ts

I renamed the sim to `drk_sheet_sim` to better match the other sims (there's also a good chance I add <100 support in the future), and remembered to make it dump blood if the fight is almost over. I also added a bunch of semi-colons.

[DRK Sim] Dump blood at end of fight, rename sim files

---

packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/gear_edit_toolbar.ts

Toolbar sub-items are hidden by default, but can be opened by clicking the button. Does not auto-close since someone might want to look around while having a toolbar item open.

Finish polishing new toolbar UI

---

CONTRIBUTING.md
README.md

Mentioning ESLint, and updating some of the text around implementing a new sim to make it clearer that it can be implemented in TS if simple enough even for non-healer jobs.

Update contributing and readme

---

packages/frontend/src/scripts/sims/sim_guis.ts
packages/frontend/src/scripts/sims/tank/pldsks_sheet_sim_ui.ts

Hi, I've restored the paladin sks sim's settings suite via the new ui class.
Hopefully this will pass lint - I've been having some trouble testing locally which I think I've resolved.

Restored PLD SKS Sim Settings Gui

---

packages/backend-resolver/src/server_builder.ts
packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/ads.ts

- Add placement for single-column layout
- add additional sizes to existing ads so that smaller ads can appear
- add analytics events
- don't inject on embeds pages

Ads revision

---

package-lock.json
packages/frontend/package.json
packages/frontend/src/index.html
packages/frontend/webpack.config.js

Inject some initial CSS
Depends on Beasties bug fix to work correctly. 
Also checks light mode preference earlier.

Reduce FUOC on initial load

---

packages/frontend/src/scripts/components/sheet.ts

Fix toolbar not being easily draggable in one-column layout

---

packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/gear_edit_toolbar.ts
packages/frontend/src/scripts/components/materia.ts

Redo materia fill popout so that it isn't too wide on mobile, fix a bug

---

packages/core/src/sims/tank/drk/drk_actions.ts

[DRK Sim] 7.1 potency updates

---

packages/core/src/sims/default_sims.ts
packages/core/src/sims/healer/healer_mp.ts
packages/frontend/src/scripts/sims/healer/healer_mp_sim_ui.ts
packages/frontend/src/scripts/sims/sim_guis.ts

I haven't set it to show by default since it's pretty basic but it should be useful.

Added a basic healer MP economy calculator

---

packages/core/src/sims/melee/vpr/vpr_sheet_sim.ts

Uses reawaken if possible before the fight ends

End of Fight logic for VPR

---

packages/core/src/external/etro_import.ts
packages/core/src/sheet.ts
packages/core/src/test/export_import_tests.ts
packages/xivmath/src/geartypes.ts

Add race and party size to individual set exports; add tests

---

packages/core/src/sims/tank/war/war_actions.ts
packages/core/src/sims/tank/war/war_sheet_sim.ts
packages/core/src/sims/tank/war/war_types.ts

I tested all of the levels, and it Seems Good. It's not doing anything it shouldn't, numbers look accurate, etc.
UWU:
TEA:
DSR:

[WAR Sim] Add support for 70-90 WAR

---

packages/core/src/sims/tank/pld/pld_actions.ts
packages/core/src/sims/tank/pld/pld_sheet_sim.ts
packages/core/src/sims/tank/pld/pld_types.ts

Everything seems to work, it's not using incorrect abilities, and the numbers look correct and expected. (and I didn't break anything for level 100 PLD, for any sim)
UWU:
TEA:
DSR:

[PLD Sim] 70, 80, 90 support for PLD

---

packages/core/src/imports/imports.ts
packages/core/src/test/import_tests.ts
packages/core/src/util/sheet_utils.ts
packages/frontend/src/scripts/base_ui.ts
packages/frontend/src/scripts/components/import_sheet.ts
packages/frontend/src/scripts/components/sheet.ts
packages/frontend/src/scripts/nav_hash.ts

This also makes the code for importing more common with the code for navigation.

Fix imports with new-style links

---

packages/frontend/src/scripts/components/meld_solver_modal.ts

Closes https://github.com/xiv-gear-planner/gear-planner/issues/374
This adds a warning to the meld solver when the number of melds it needs to solve for is above 23 (the maximum number without pentameld items). While it's an 'unscientific' number (24 melds would be easy to solve for), it displays the warning when the user starts getting into difficult territory.
It will dynamically check if 'Overwrite existing materia' is set and display the warning if enabling this setting pushes it over the limit of 23.

Add warning to meld solver for solving pentameld sets

---

packages/common-ui/styles/common.less
packages/core/src/customgear/custom_item.ts
packages/core/src/datamanager_new.ts
packages/core/src/sims/cycle_sim.ts
packages/frontend/src/scripts/components/items.ts
packages/frontend/src/scripts/components/materia.ts
packages/frontend/src/style.less
packages/xivmath/src/geartypes.ts

Add placeholder background gradients to item icons, fit materia tooltip

---

packages/common-ui/styles/common.less

Fix item table changing size when collapsing

---

packages/common-ui/src/analytics/analytics.ts
packages/core/src/datamanager_new.ts

Log dataManager errors, improve resilency of error reporting function.

Error logging for datamanager

---

packages/backend-resolver/src/server_builder.ts
packages/core/src/util/sheet_utils.ts
packages/frontend/src/scripts/base_ui.ts
packages/frontend/src/scripts/components/import_sheet.ts
packages/frontend/src/scripts/embed.ts
packages/frontend/src/scripts/nav_hash.ts

Display better error when there is an invalid onlySetIndex, improve errors in general

---

packages/core/src/sheet.ts
packages/frontend/src/scripts/components/custom_item_manager.ts
packages/frontend/src/scripts/components/gear_edit_toolbar.ts
packages/frontend/src/scripts/components/items.ts
packages/frontend/src/scripts/components/sheet.ts
packages/util/src/inactivitytimer.ts

Fixes #526
Also fixes an issue where clicking the "higher relics" checkbox on the weapons table might cause the table to collapse/expand.

Improvements to gear filtering

---

packages/common-ui/styles/common.less
packages/frontend/src/scripts/sims/multicyclesim_ui.ts

Put the rotation selector left/above the summary table.

Rearrange cycle sim results

---

.idea/inspectionProfiles/Project_Default.xml
packages/common-ui/src/components/expandy_text.ts
packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/sheet.ts

Description expander

---

packages/common-ui/styles/common.less
packages/core/src/gear.ts
packages/frontend/src/scripts/components/items.ts
packages/frontend/src/scripts/components/sheet.ts
packages/xivmath/src/geartypes.ts
packages/xivmath/src/xivconstants.ts
packages/xivmath/src/xivstats.ts

Show effective food bonuses

---

packages/common-ui/src/components/util.ts
packages/common-ui/src/util/types.ts
packages/frontend/src/scripts/base_ui.ts

Show a hyperlink to open full sheet for bad embeds

---

packages/frontend/src/index.html

Just wanted to make this a little more up to date and accurate.

Update index page message to be a little less outdated

---

packages/core/src/sims/melee/mnk/mnk_sim.ts

Reverts xiv-gear-planner/gear-planner#565

Revert "Fix blitz window entry for "-3" opos"

---

packages/core/src/test/sims/sim_tests.ts

Fixes #269 
Makes sure that every sim can at least run.

Test every sim

---

.idea/inspectionProfiles/Project_Default.xml
packages/core/src/gear.ts
packages/core/src/sheet.ts
packages/core/src/util/sheet_utils.ts
packages/frontend/src/scripts/components/sheet.ts
packages/frontend/src/scripts/components/sheet_info_modal.ts
packages/frontend/src/scripts/sims/components/simple_tables.ts
packages/frontend/src/scripts/sims/count_sim_gui.ts
packages/frontend/src/scripts/sims/multicyclesim_ui.ts
packages/frontend/src/style.less
packages/xivmath/src/geartypes.ts
packages/xivmath/src/xivmath.ts

Not a particularly pretty UI, but exposes the information for those who need it.
Closes #344 and #330

Add sheet/set info modal

---

packages/common-ui/styles/common.less
packages/frontend/src/scripts/sims/components/result_settings.ts
packages/frontend/src/scripts/sims/healer/sch_sheet_sim_ui.ts

Fix some issues with sim config UIs

---

.idea/inspectionProfiles/Project_Default.xml
packages/common-ui/styles/common.less
packages/common-ui/styles/gauge.less
packages/core/src/sims/sim_types.ts
packages/frontend/src/scripts/sims/common/sim_ui_utils.ts
packages/frontend/src/scripts/sims/healer/sch_sheet_sim_ui.ts
packages/frontend/src/scripts/sims/healer/whm_new_sheet_sim_ui.ts
packages/frontend/src/scripts/sims/melee/mnk/mnk_sim_ui.ts
packages/frontend/src/scripts/sims/multicyclesim_ui.ts
packages/frontend/src/style.less

- Some fixes for the new sim results UI
- Sim results UI now only scrolls the actions table
- More gauges have been refactored to use CSS instead of inline styles

Gauge and other sim UI refactors

---

packages/frontend/src/scripts/components/meld_solver_modal.ts

Fix for https://github.com/xiv-gear-planner/gear-planner/issues/582

Fix solver not preserving locked slots

---

packages/backend-resolver/src/server_builder.ts
packages/backend-resolver/src/test/endpoints_test.ts
packages/core/src/external/static_bis.ts
packages/frontend/src/scripts/nav_hash.ts

- Refactor previews code
- Fix a bug with validateEmbed
- Add previews for bisbrowser
- Add tests for validateEmbed

Server improvements

---

packages/common-ui/styles/common.less
packages/frontend/src/scripts/components/job_icon.ts
packages/frontend/src/scripts/components/saved_sheet_picker.ts

Saved sheet picker multijob

---

packages/backend-resolver/src/preload_helpers.ts
packages/backend-resolver/src/server_builder.ts
packages/backend-resolver/src/test/endpoints_test.ts

Add additional image preloads:
- Multi-job sheets will preload job icons for that role
- BiS root directory will preload all job icons
Closes #591

Additional preload URLs

---

packages/common-ui/src/table/tables.ts
packages/frontend/src/scripts/sims/components/ability_used_table.ts
packages/frontend/src/style.less

- Aligns on the decimal point
- Reduced damage from two decimal places to one

Improve alignment of numbers on sim results table

---

packages/backend-resolver/src/server_builder.ts
packages/backend-resolver/src/test/endpoints_test.ts

Fix lack of unhandled rejection handler causing the fastify instance to crash in some specific circumstances.

Fix fastify crash

---

packages/frontend/src/scripts/components/items.ts

Fix lack of stat cap tooltip for wd

---

packages/core/src/customgear/custom_item.ts
packages/core/src/sheet.ts
packages/core/src/test/custom_items_test.ts
packages/xivmath/src/geartypes.ts

Fix custom items sometimes allowing materia to be equipped when they are downsynced.
Also fixes the materia count cell showing an error.

Fix custom item sync

---

packages/frontend/src/scripts/components/items.ts

Fix the display bug with empty relics, as well as a minor bug with ilvl display ranges

---

packages/core/src/external/xivapi.ts

Fix xivApiGetList

---

packages/frontend/src/scripts/sims/common/potency_ratio_ui.ts

Center the potency ratio results

---

packages/core/src/nav/common_nav.ts

Fix broken preview due to multiple unescapes

---

.idea/inspectionProfiles/Project_Default.xml
packages/common-ui/styles/common.less
packages/frontend/src/index.html

This slightly refactors the way that the item tables work, so should be tested on other browsers as well.

Fix toolbar dragging, other iOS fixes

---

packages/frontend/src/scripts/components/ads.ts

Refactors the code to make it less likely for an ad to appear over/under the content, it should only appear in what would otherwise be unused space.

Refactor ad code

---

packages/core/src/gear.ts
packages/core/src/sheet.ts
packages/frontend/src/scripts/components/items.ts
packages/xivmath/src/geartypes.ts
packages/xivmath/src/xivconstants.ts

show-hide for food, food relevancy setting

---

packages/common-ui/src/table/tables.ts
packages/frontend/src/scripts/components/items.ts

Fixes https://discord.com/channels/277897135515762698/1159570343971786822/1375331456146215022

Fix clicking on the food toggle, slightly improve gear table hover titles

---

packages/common-ui/styles/gauge.less
packages/frontend/src/scripts/sims/healer/ast_sheet_sim_ui.ts
packages/frontend/src/scripts/sims/healer/sch_sheet_sim_ui.ts
packages/frontend/src/scripts/sims/melee/sam/sam_lvl100_sim_ui.ts
packages/frontend/src/scripts/sims/tank/gnb_sheet_sim_ui.ts

Closes #251 
This refactors nearly all of the existing gauges to use CSS instead of hardcoded styling.

Gauge refactors

---

packages/core/src/datamanager_new.ts
packages/frontend/src/scripts/components/meld_solver_modal.ts

Fixes #652 
Also improves buggy layout when you meld solve but end up with a worse result due to locking GCD.

Fix HQ item bug, also fix some solver result styling

---

.github/workflows/frontend_docker.yml

Fix doc generation

---

packages/core/src/datamanager_new.ts
packages/core/src/test/datamanager_tests.ts

Fix HQ stats

---

.github/workflows/math_frontend_docker.yml
.idea/inspectionProfiles/Project_Default.xml
package.json
packages/account-service-client/src/accountsvc.ts
packages/common-ui/src/components/forms/form_elements.ts
packages/common-ui/src/components/forms/validating_form.ts
packages/common-ui/src/components/util.ts
packages/common-ui/styles/common.less
packages/frontend/package.json
packages/frontend/src/scripts/account/account_state.ts
packages/frontend/src/scripts/account/components/account_components.ts
packages/frontend/src/scripts/components/new_sheet_form.ts
packages/frontend/src/scripts/main.ts
packages/frontend/src/style.less
packages/frontend/tsconfig.json

Relates to #649 
Adds an account management UI but not accessible from the normal UI. You can run `showAccountModal()` in the browser console to see it.

Add WIP account management stuff

---

packages/common-ui/src/components/forms/validating_form.ts
packages/common-ui/src/components/top_menu.ts
packages/common-ui/src/components/util.ts
packages/common-ui/styles/common.less
packages/frontend/src/index.html
packages/frontend/src/scripts/account/account_state.ts
packages/frontend/src/scripts/account/components/account_components.ts
packages/frontend/src/scripts/main.ts

Still not visible, but is much better now. Top menu button will display whether you are logged in or not.

Improve account management UI

---

packages/core/src/gear.ts
packages/frontend/src/scripts/components/sheet.ts

- Make set name/description part of the undo checkpoint
- Fix bug with logic that allows input elements to handle undo/redo

Improve undo with regards to set name/desc

---

packages/core/src/persistence/saved_sheets.ts

Temporary workaround to allow your sheets browser to not get bricked if you use the sheet-sync branch and then switch back to main.

Forwards-compat for sheet syncing

---

packages/core/src/data_api_client.ts
packages/core/src/datamanager.ts
packages/core/src/datamanager_new.ts
packages/core/src/external/etro_import.ts
packages/core/src/gear.ts
packages/core/src/sheet.ts
packages/core/src/sims/sim_types.ts
packages/frontend/src/scripts/components/sheet.ts
packages/frontend/src/scripts/sims/sim_guis.ts
packages/xivmath/src/geartypes.ts

This is partially hampered by the fact that the Data API properties are not marked as required in the swagger spec, so I am having to `!` everything or use the `NonNullable<T>` wrapper.

Partial progress on enabling ts-strict

---

packages/core/src/datamanager_new.ts
packages/core/src/test/item_stats_tests.ts

Fix item sync for offhands

---

packages/data-api-client/src/dataapi.ts

Relates to https://github.com/xiv-gear-planner/xivgear-data-api/pull/15

Reduce the amount of fields in icon struct

---

packages/core/src/sims/cycle_sim.ts
packages/core/src/sims/healer/whm_new_sheet_sim.ts
packages/core/src/test/sims/sim_tests.ts

- Fix infinite loop in WHM sim
- Improve circuit breaker logic

Whm loop fix

---

packages/core/src/sheet.ts
packages/core/src/solving/gearset_generation.ts
packages/core/src/solving/sim_runner.ts
packages/frontend/src/scripts/components/gear_edit_toolbar.ts
packages/frontend/src/scripts/components/meld_solver_modal.ts
packages/frontend/src/scripts/components/meldsolver.ts
packages/frontend/src/scripts/workers/meld_generation_worker.ts
packages/frontend/src/scripts/workers/simulation_worker.ts

Adds a food solver to the meld solver
e.g.

[Feature] Add ability to solve food to meld solver

---

packages/common-ui/src/components/modal.ts
packages/core/src/solving/gearset_generation.ts
packages/frontend/src/scripts/components/meld_solver_modal.ts

Feels way more consistent with the other option, and allows a more seamless solve of everything.

Minor food solver UX change: Overwrite food instead of solve food

---

packages/common-ui/src/components/expandy_text.ts
packages/frontend/src/scripts/analytics/analytics_helpers.ts
packages/frontend/src/scripts/components/ads.ts
packages/frontend/src/scripts/main.ts

Provides better analytics of window sizing.

analytics improvements and fixes

---

package.json
packages/core/src/sims/common/cooldown_manager.ts
packages/core/src/sims/cycle_sim.ts
packages/core/src/sims/sim_types.ts
packages/core/src/test/sims/cycle_processor_tests.ts

Fix cooldowns where a level modifier changes the action ID

---

packages/frontend/src/scripts/nav_hash.ts

Replace %7C with | when loading a page automatically

Auto rewrite URL
